title: "Jahnavi Jonnalagadda"
email: jahnavi30nov@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" 
url: "/portfolio-template" 
twitter_username: Jahnavi_30
github_username:  Jahnavi-Jonnalagadda

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
